apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sec-web
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: seccrsoldout.azurecr.io/minjoon-koo/pipe_deploy-web:latest
        imagePullPolicy: Always
        lifecycle:
        name: sec-web
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
